POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "A cool blog",
    "author": "Generic person",
    "url": "http://blog.com/cool-blog",
    "likes": 4
}